name: Feature Request
description: Suggest a new feature or improvement
title: "[Feature]: "
labels: ["enhancement"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for suggesting a feature! Please describe your idea in detail.

  - type: textarea
    id: problem
    attributes:
      label: Problem or Use Case
      description: Is your feature request related to a problem? Please describe.
      placeholder: "I'm always frustrated when..."
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: Proposed Solution
      description: Describe the solution you'd like.
      placeholder: Describe your ideal solution...
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives Considered
      description: Describe any alternative solutions or features you've considered.
      placeholder: Other approaches you've thought about...

  - type: dropdown
    id: priority
    attributes:
      label: Priority
      description: How important is this feature to you?
      options:
        - Nice to have
        - Important
        - Critical for my workflow
    validations:
      required: true

  - type: checkboxes
    id: privacy
    attributes:
      label: Privacy Considerations
      description: KlipPal is privacy-first. Please confirm your feature aligns with this philosophy.
      options:
        - label: This feature does not require network access or data collection
          required: true

  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: Add any other context, mockups, or screenshots about the feature request here.
